name: BrowserStack Test Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_file: [
          'tests/test_web_app.py',
          'tests/mobile/test_mobile_app.py'
        ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-xdist
          pip install -e .
      
      - name: Create directories
        run: |
          mkdir -p test-results
          mkdir -p screenshots
      
      - name: Run tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          # Convertir el nombre del test a formato de archivo seguro
          TEST_RESULT_FILE=$(echo "${{ matrix.test_file }}" | tr '/' '_' | tr ':' '_')
          pytest -v "${{ matrix.test_file }}" \
            --junitxml=test-results/${TEST_RESULT_FILE}_results.xml
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.run_number }}
          path: screenshots/
          retention-days: 3
          if-no-files-found: ignore
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: test-results/
          retention-days: 3
          if-no-files-found: ignore
