name: BrowserStack Test Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Permite que otros tests continúen si uno falla
      matrix:
        test_file: [
          'tests/test_web_app.py::TestWebApp::test_login_flow',
          'tests/test_web_app.py::TestWebApp::test_search_feature',
          'tests/mobile/test_mobile_app.py::TestMobileApp::test_mobile_navigation'
        ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-xdist
      
      - name: Create screenshots directory
        run: mkdir -p screenshots
      
      - name: Run tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          pytest -v ${{ matrix.test_file }} --junitxml=test-results/${{ runner.os }}-$(echo ${{ matrix.test_file }} | sed 's/[^a-zA-Z0-9]/_/g').xml
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots-${{ runner.os }}-${{ github.run_id }}
          path: screenshots/
          retention-days: 5
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}-${{ github.run_id }}
          path: test-results/
          retention-days: 5
