name: BrowserStack Test Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - test_file: "tests/test_web_app.py::TestWebApp::test_login_flow"
            capabilities: '{"browserName": "Chrome", "browserVersion": "latest", "platformName": "Windows"}'
            artifact_suffix: "web_login"
          - test_file: "tests/test_web_app.py::TestWebApp::test_search_feature"
            capabilities: '{"browserName": "Firefox", "browserVersion": "latest", "platformName": "Windows"}'
            artifact_suffix: "web_search"
          - test_file: "tests/mobile/test_mobile_app.py::TestMobileApp::test_mobile_navigation"
            capabilities: '{"browserName": "chrome", "platformName": "android", "deviceName": "Samsung Galaxy S22", "osVersion": "13.0", "realMobile": "true"}'
            artifact_suffix: "mobile_nav"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Create directories
        run: |
          mkdir -p test-results/${{ matrix.config.artifact_suffix }}
          mkdir -p screenshots/${{ matrix.config.artifact_suffix }}
      
      - name: Run test
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          SCREENSHOT_DIR: "screenshots/${{ matrix.config.artifact_suffix }}"
        run: |
          pytest -v "${{ matrix.config.test_file }}" \
            --junitxml=test-results/${{ matrix.config.artifact_suffix }}/results.xml
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.config.artifact_suffix }}-${{ github.run_id }}
          path: screenshots/${{ matrix.config.artifact_suffix }}
          retention-days: 3
          if-no-files-found: ignore
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.config.artifact_suffix }}-${{ github.run_id }}
          path: test-results/${{ matrix.config.artifact_suffix }}
          retention-days: 3
          if-no-files-found: ignore
