name: BrowserStack Test Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - test_file: "tests/test_web_app.py::TestWebApp::test_login_flow"
            capabilities: '{"browserName": "Chrome", "browserVersion": "latest", "platformName": "Windows"}'
          - test_file: "tests/test_web_app.py::TestWebApp::test_search_feature"
            capabilities: '{"browserName": "Firefox", "browserVersion": "latest", "platformName": "Windows"}'
          - test_file: "tests/mobile/test_mobile_app.py::TestMobileApp::test_mobile_navigation"
            capabilities: '{"browserName": "chrome", "platformName": "android", "deviceName": "Samsung Galaxy S22"}'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-xdist
      
      - name: Create directories
        run: |
          mkdir -p test-results
          mkdir -p screenshots
      
      - name: Run test
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          TEST_CAPABILITIES: ${{ matrix.capabilities }}
        run: |
          # Convertir el nombre del test a formato de archivo seguro
          TEST_RESULT_FILE=$(echo "${{ matrix.config.test_file }}" | tr '/:' '_')
          pytest -v "${{ matrix.config.test_file }}" \
            --junitxml=test-results/${TEST_RESULT_FILE}_results.xml
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.run_id }}-${{ github.run_attempt }}
          path: screenshots/
          retention-days: 3
          if-no-files-found: ignore
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}-${{ github.run_attempt }}
          path: test-results/
          retention-days: 3
          if-no-files-found: ignore
